name: Run Pytest

on:
    workflow_dispatch: # manual
    pull_request: # or on pull-request
        types: # type of pull requests it'll trigger on
            - opened
            - reopened
            - synchronize
            - ready_for_review

jobs:
    pytest:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout the repo 
              uses: actions/checkout@v3
            - name: Set up Python
              uses: actions/setup-python@v3
              with:
                python-version: "3.x"
            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip # ensure eveything is up to date
                pip install -r requirements.txt
            - name: Test with pytest
              run: pytest